### ISSUE TITLE
how to provide SSL details with KSQLDB URL

### ISSUE THREAD

**Issue by ansarizakir** [rmoff/vsc-ksql#14] opened 2022-10-11 15:23 UTC
Hi,

We are using Confluent 6.1 and want to provide separate UI for KSQLDB for users. This tool looks good but how to provide SSL details, I can see only URL which is KSQLDB URL needs to provide . Can you please guide how and where to provide SSL details with KSQLDB URL.

**Comment by rmoff** [comment] 2022-10-11 15:39
Duplicate of #12

**Closed by rmoff** 2022-10-11 15:39 UTC

**Comment by rmoff** [comment] 2022-10-12 08:38
This is not implemented in the plugin currently.
